### ISSUE TITLE
Wrong variable identifier for getting jump range from EDDI

### ISSUE THREAD

**Issue by kaimi** [sc-pulgan/ED-NeutronRouter#3]
`maxjump` is used when the correct identifier would be `maxjumprange`.

https://github.com/sc-pulgan/ED-NeutronRouter/blob/d4d1d6cd4930041d3fb525aea551c635c31aef3e/Project/EDDIJumpRange.cs#L26

That doesn’t fix the problem that EDDI only saves the _max_ range, not the current one (incuding a full fuel tank).

**Comment by Pulganosaure** [comment]
I just saw your message... I'm really sorry i never receive any notif about it. didn't expect someone found my project so i never checked the pull requests

**Comment by kaimi** [comment]
Haha :)

Well I’ve found it and it has served me well, so … thanks!

**Comment by Pulganosaure** [comment]
you're fix should make it more stable. I probably gonna hide my project. I'm far to be a good programmer and more particular in C# ^^

**Comment by kaimi** [comment]
Well there’s only one way to get better, and that’s practice. And you can get useful feedback here.

Plus I appreciate not having to write this myself :p
